# These are supported funding model platforms

github: [newcode-dev]
patreon: newcode-dev
open_collective: newcode-dev
ko_fi: newcode-dev
tidelift: newcode-dev
community_bridge: newcode-dev
liberapay: newcode-dev
issuehunt: newcode-dev
otechie: newcode-dev
custom: ["https://newcode.dev/donate", "https://buymeacoffee.com/newcode-dev"] 